languages_dict = {
	'ace_Arab' : 'Acehnese',
	'ace_Latn' : 'Acehnese', 
	'acm_Arab' : 'Mesopotamian Arabic', 
	'acq_Arab' : 'Ta izzi-Adeni Arabic', 
	'aeb_Arab' : 'Tunisian Arabic', 
	'afr_Latn' : 'Afrikaans', 
	'ajp_Arab' : 'South Levantine Arabic', 
	'aka_Latn' : 'Akan', 
	'amh_Ethi' : 'Amharic', 
	'apc_Arab' : 'North Levantine Arabic', 
	'arb_Arab' : 'Standard Arabic', 
	'ars_Arab' : 'Najdi Arabic', 
	'ary_Arab' : 'Moroccan Arabic', 
	'arz_Arab' : 'Egyptian Arabic', 
	'asm_Beng' : 'Assamese', 
	'ast_Latn' : 'Asturian', 
	'awa_Deva' : 'Awadhi', 
	'ayr_Latn' : 'Aymara', 
	'azb_Arab' : 'South Azerbaijani', 
	'azj_Latn' : 'North Azerbaijani', 
	'bak_Cyrl' : 'Bashkir', 
	'bam_Latn' : 'Bambara', 
	'ban_Latn' : 'Balinese', 
	'bel_Cyrl' : 'Belarusian', 
	'bem_Latn' : 'Bemba', 
	'ben_Beng' : 'Bengali',
	'bho_Deva' : 'Bhojpuri', 
	'bjn_Arab' : 'Banjar', 
	'bjn_Latn' : 'Banjar', 
	'bod_Tibt' : 'Tibetan', 
	'bos_Latn' : 'Bosnian', 
	'bug_Latn' : 'Buginese', 
	'bul_Cyrl' : 'Bulgarian', 
	'cat_Latn' : 'Catalan', 
	'ceb_Latn' : 'Cebuano', 
	'ces_Latn' : 'Czech', 
	'cjk_Latn' : 'Chokwe', 
	'ckb_Arab' : 'Central Kurdish (Sorani)', 
	'crh_Latn' : 'Crimean Tatar', 
	'cym_Latn' : 'Welsh', 
	'dan_Latn' : 'Danish', 
	'deu_Latn' : 'German', 
	'dik_Latn' : 'Southwestern Dinka', 
	'dyu_Latn' : 'Dyula', 
	'dzo_Tibt' : 'Dzongkha', 
	'ell_Grek' : 'Greek', 
	'eng_Latn' : 'English', 
	'epo_Latn' : 'Esperanto', 
	'est_Latn' : 'Estonian', 
	'eus_Latn' : 'Basque', 
	'ewe_Latn' : 'Ewe', 
	'fao_Latn' : 'Faroese', 
	'pes_Arab' : 'Iranian Persian', 
	'fij_Latn' : 'Fijian', 
	'fin_Latn' : 'Finnish', 
	'fon_Latn' : 'Fon', 
	'fra_Latn' : 'French', 
	'fur_Latn' : 'Friulian', 
	'fuv_Latn' : 'Nigerian Fulfulde', 
	'gla_Latn' : 'Scottish Gaelic', 
	'gle_Latn' : 'Irish', 
	'glg_Latn' : 'Galician', 
	'grn_Latn' : 'Guarani', 
	'guj_Gujr' : 'Gujarati', 
	'hat_Latn' : 'Haitian Creole', 
	'hau_Latn' : 'Hausa', 
	'heb_Hebr' : 'Hebrew', 
	'hin_Deva' : 'Hindi', 
	'hne_Deva' : 'Chhattisgarhi', 
	'hrv_Latn' : 'Croatian', 
	'hun_Latn' : 'Hungarian', 
	'hye_Armn' : 'Armenian', 
	'ibo_Latn' : 'Igbo', 
	'ilo_Latn' : 'Ilocano', 
	'ind_Latn' : 'Indonesian', 
	'isl_Latn' : 'Icelandic', 
	'ita_Latn' : 'Italian', 
	'jav_Latn' : 'Javanese', 
	'jpn_Jpan' : 'Japanese', 
	'kab_Latn' : 'Kabyle', 
	'kac_Latn' : 'Jingpho (Kachin)', 
	'kam_Latn' : 'Kamba', 
	'kan_Knda' : 'Kannada', 
	'kas_Arab' : 'Kashmiri', 
	'kas_Deva' : 'Kashmiri', 
	'kat_Geor' : 'Georgian', 
	'knc_Arab' : 'Kanuri', 
	'knc_Latn' : 'Kanuri', 
	'kaz_Cyrl' : 'Kazakh', 
	'kbp_Latn' : 'Kabiyè', 
	'kea_Latn' : 'Kabuverdianu (Cape Verde Creole)',
	'khm_Khmr' : 'Khmer', 
	'kik_Latn' : 'Kikuyu', 
	'kin_Latn' : 'Kinyarwanda', 
	'kir_Cyrl' : 'Kyrgyz', 
	'kmb_Latn' : 'Kimbundu', 
	'kon_Latn' : 'Kongo', 
	'kor_Hang' : 'Korean', 
	'kmr_Latn' : 'Northern Kurdish (Kurmanji)', 
	'lao_Laoo' : 'Lao', 
	'lvs_Latn' : 'Standard Latvian', 
	'lij_Latn' : 'Ligurian', 
	'lim_Latn' : 'Limburgish', 
	'lin_Latn' : 'Lingala',
	'lit_Latn' : 'Lithuanian', 
	'lmo_Latn' : 'Lombard', 
	'ltg_Latn' : 'Latgalian', 
	'ltz_Latn' : 'Luxembourgish', 
	'lua_Latn' : 'Luba-Lulua', 
	'lug_Latn' : 'Ganda', 
	'luo_Latn' : 'Luo', 
	'lus_Latn' : 'Mizo (Lushai)', 
	'mag_Deva' : 'Magahi', 
	'mai_Deva' : 'Maithili', 
	'mal_Mlym' : 'Malayalam', 
	'mar_Deva' : 'Marathi', 
	'min_Latn' : 'Minangkabau', 
	'mkd_Cyrl' : 'Macedonian', 
	'plt_Latn' : 'Plateau Malagasy', 
	'mlt_Latn' : 'Maltese', 
	'mni_Beng' : 'Manipuri (Meitei)', 
	'khk_Cyrl' : 'Halh Mongolian', 
	'mos_Latn' : 'Mooré', 
	'mri_Latn' : 'Māori', 
	'zsm_Latn' : 'Malay (generic)', 
	'mya_Mymr' : 'Burmese', 
	'nld_Latn' : 'Dutch', 
	'nno_Latn' : 'Norwegian Nynorsk', 
	'nob_Latn' : 'Norwegian Bokmål', 
	'npi_Deva' : 'Nepali (India)', 
	'nso_Latn' : 'Northern Sotho', 
	'nus_Latn' : 'Nuer', 
	'nya_Latn' : 'Nyanja (Chichewa)', 
	'oci_Latn' : 'Occitan', 
	'gaz_Latn' : 'West Central Oromo', 
	'ory_Orya' : 'Odia', 
	'pag_Latn' : 'Pangasinan', 
	'pan_Guru' : 'Punjabi', 
	'pap_Latn' : 'Papiamento', 
	'pol_Latn' : 'Polish', 
	'por_Latn' : 'Portuguese', 
	'prs_Arab' : 'Dari Persian', 
	'pbt_Arab' : 'Southern Pashto', 
	'quy_Latn' : 'Ayacucho Quechua', 
	'ron_Latn' : 'Romanian', 
	'run_Latn' : 'Rundi (Kirundi)', 
	'rus_Cyrl' : 'Russian', 
	'sag_Latn' : 'Sango', 
	'san_Deva' : 'Sanskrit', 
	'sat_Beng' : 'Santali', 
	'scn_Latn' : 'Sicilian', 
	'shn_Mymr' : 'Shan', 
	'sin_Sinh' : 'Sinhala', 
	'slk_Latn' : 'Slovak',
	'slv_Latn' : 'Slovenian', 
	'smo_Latn' : 'Samoan', 
	'sna_Latn' : 'Shona', 
	'snd_Arab' : 'Sindhi', 
	'som_Latn' : 'Somali', 
	'sot_Latn' : 'Southern Sotho', 
	'spa_Latn' : 'Spanish', 
	'als_Latn' : 'Tosk Albanian', 
	'srd_Latn' : 'Sardinian', 
	'srp_Cyrl' : 'Serbian', 
	'ssw_Latn' : 'Swati',
	'sun_Latn' : 'Sundanese', 
	'swe_Latn' : 'Swedish', 
	'swh_Latn' : 'Swahili', 
	'szl_Latn' : 'Silesian', 
	'tam_Taml' : 'Tamil', 
	'tat_Cyrl' : 'Tatar', 
	'tel_Telu' : 'Telugu', 
	'tgk_Cyrl' : 'Tajik', 
	'tgl_Latn' : 'Tagalog', 
	'tha_Thai' : 'Thai', 
	'tir_Ethi' : 'Tigrinya', 
	'taq_Latn' : 'Tamasheq (Latin)', 
	'taq_Tfng' : 'Tamasheq (Tifinagh)', 
	'tpi_Latn' : 'Tok Pisin', 
	'tsn_Latn' : 'Tswana', 
	'tso_Latn' : 'Tsonga', 
	'tuk_Latn' : 'Turkmen', 
	'tum_Latn' : 'Tumbuka', 
	'tur_Latn' : 'Turkish', 
	'twi_Latn' : 'Twi', 
	'tzm_Tfng' : 'Central Atlas Tamazight', 
	'uig_Arab' : 'Uyghur', 
	'ukr_Cyrl' : 'Ukrainian', 
	'umb_Latn' : 'Umbundu', 
	'urd_Arab' : 'Urdu', 
	'uzn_Latn' : 'Northern Uzbek', 
	'vec_Latn' : 'Venetian', 
	'vie_Latn' : 'Vietnamese', 
	'war_Latn' : 'Waray', 
	'wol_Latn' : 'Wolof', 
	'xho_Latn' : 'Xhosa', 
	'ydd_Hebr' : 'Eastern Yiddish', 
	'yor_Latn' : 'Yoruba', 
	'yue_Hant' : 'Cantonese',
	'zho_Hans' : 'Mandarin Chinese', 
	'zho_Hant' : 'Mandarin Chinese',
	'zul_Latn' : 'Zulu' 
}

languages = dict(sorted(languages_dict.items(), key=lambda item: item[1]))